### ISSUE TITLE
Trace missing on map

### ISSUE THREAD

**Issue by ToeBee** [kartaview/openstreetcam.org#88] opened 2016-12-10 07:33 UTC
I was looking at coverage today and saw some blank places on the map where I thought I had already uploaded images. I was about to re-upload when I noticed that in JOSM, the plugin was showing images along these roads. But they are not showing as having coverage on the map.

Possibly a re-opening of #1 although that may have just been the weird tile display problem (#36). This is definitely not #36 though. The trace doesn't show up no matter where you pan/zoom.

Some specific examples:
* http://openstreetcam.org/details/8916/590 should indicate coverage through [Wathena](http://openstreetcam.org/map/@39.76305119001318,-94.9536645412445,16z)
* http://openstreetcam.com/details/24799/2500 should indicate coverage from Kansas City to Columbia, MO [along I-70](http://openstreetcam.com/map/@38.98369843276727,-93.7576675415039,11z)
* Both http://openstreetcam.com/details/8454/1031 and http://openstreetview.com/details/8471/527 should indicate coverage along US 36 from the [Colorado border and St. Francis](http://openstreetcam.com/map/@39.75454778633137,-101.9317102432251,14z).

**Comment by nikolajsheller** [comment] 2017-01-22 21:12
I am seeing the same issue. Some of my traces are not shown on the map, and the traces that are shown on the map cannot be selected correctly, i.e. I cannot set a dot, and regardless of where I click on the trace, it shows the last image of the trace.

Does not show up on map:
http://openstreetcam.org/details/29075/1

Only shows last image of trace:
http://openstreetcam.org/details/29082

**Comment by ToeBee** [comment] 2017-08-01 19:40
All of my examples now show up correctly on the map.

**Comment by JiudanZheng** [comment] 2020-12-21 08:34
Since @ToeBee has confirmed that the tracks have shown up correctly, we will close this ticket.

**Closed** 2020-12-25 09:10 UTC
Labels: bug
